apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: default
data:
 index.html: |
   <html>
   <head><title>THANK YOU FOR OPPORTUNITY AppScrip</title></head>
   <body>
   <h1>THANK YOU FOR OPPORTUNITY AppScrip</h1>
   </body>
   </html>